
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'FACA MAIS MOSTRE NUM PONTO SER VARprograma : cmdscmds : cmd cmds\n            | cmdcmd : FACA VAR SER NUM PONTOcmd : MOSTRE VAR PONTOcmd : FACA VAR SER VAR MAIS VAR PONTO'
    
_lr_action_items = {'FACA':([0,3,10,14,16,],[4,4,-5,-4,-6,]),'MOSTRE':([0,3,10,14,16,],[5,5,-5,-4,-6,]),'$end':([1,2,3,6,10,14,16,],[0,-1,-3,-2,-5,-4,-6,]),'VAR':([4,5,9,13,],[7,8,11,15,]),'SER':([7,],[9,]),'PONTO':([8,12,15,],[10,14,16,]),'NUM':([9,],[12,]),'MAIS':([11,],[13,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'programa':([0,],[1,]),'cmds':([0,3,],[2,6,]),'cmd':([0,3,],[3,3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> programa","S'",1,None,None,None),
  ('programa -> cmds','programa',1,'p_programa','teste.py',45),
  ('cmds -> cmd cmds','cmds',2,'p_cmds','teste.py',49),
  ('cmds -> cmd','cmds',1,'p_cmds','teste.py',50),
  ('cmd -> FACA VAR SER NUM PONTO','cmd',5,'p_cmd_atribuicao','teste.py',54),
  ('cmd -> MOSTRE VAR PONTO','cmd',3,'p_cmd_impressao','teste.py',58),
  ('cmd -> FACA VAR SER VAR MAIS VAR PONTO','cmd',7,'p_cmd_soma','teste.py',62),
]
